import { useEffect, useState } from "react";
import API from "../utils/api";
import "./ProfileChangeRequests.css";

const subjectLabels = { math: "Mathematics", physics: "Physics", chemistry: "Chemistry", biology: "Biology", english: "English", computer: "Computer Science" };
const formatSubjects = (items = []) => items.map((item) => subjectLabels[item] || item).join(", ");

export default function AdminProfileChangeRequests() {
  const [requests, setRequests] = useState([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notes, setNotes] = useState({});
  const load = async () => { try { setRequests((await API.get("/admin/profile-change-requests")).data); } catch (err) { setError(err.response?.data?.error || "Could not load profile change requests."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const review = async (request, status) => { const adminReason = notes[request.id] || ""; if (status === "Rejected" && !adminReason.trim()) return setError("A rejection reason is required."); const adminSecretCode = window.prompt(`Enter your admin secret code to ${status.toLowerCase()} this request:`) || ""; if (!adminSecretCode) return; if (status === "Applied" && !window.confirm(`Apply ${request.requestedTrack} and the requested subjects for ${request.user.name}?`)) return; setBusy(request.id); setError(""); try { await API.patch(`/admin/profile-change-requests/${request.id}`, { status, adminReason, adminSecretCode }); await load(); } catch (err) { setError(err.response?.data?.error || "Unable to update this request."); } finally { setBusy(""); } };
  if (loading) return <p>Loading profile change requests…</p>;
  return <div className="admin-change-requests"><header><span>Student accounts</span><h1>Profile Change Requests</h1><p>Review payment proof, assess the requested academic profile, and apply only after secret-code confirmation.</p></header>{error && <p className="request-error">{error}</p>}{requests.length === 0 ? <p>No profile change requests.</p> : <div className="admin-request-list">{requests.map((request) => <article key={request.id} className="admin-request-card"><div className="admin-request-top"><div><h2>{request.user.name}</h2><p>{request.user.email}{request.user.cnic ? ` · ${request.user.cnic}` : ""}</p></div><span className={`request-status ${request.status.replaceAll(" ", "-").toLowerCase()}`}>{request.status}</span></div><div className="admin-comparison"><div><small>Requested snapshot</small><strong>{request.currentTrack}</strong><p>{formatSubjects(request.currentSubjects)}</p></div><div><small>Requested change</small><strong>{request.requestedTrack}</strong><p>{formatSubjects(request.requestedSubjects)}</p></div><div><small>Current live profile</small><strong>{request.user.academicTrack || "Not set"}</strong><p>{formatSubjects(request.user.academicSubjects)}</p></div></div><p><b>Reason:</b> {request.reason}</p><p><b>Transaction ID:</b> {request.transactionId || "Not supplied"}</p>{request.receiptProof && <a className="receipt-link" href={request.receiptProof} target="_blank" rel="noreferrer">View payment proof</a>}{request.audits?.length > 0 && <div className="request-audit"><b>Audit history</b>{request.audits.map((audit) => <p key={audit.id}>{audit.action} · {new Date(audit.createdAt).toLocaleString()} · {audit.adminName || "System"}{audit.note ? ` — ${audit.note}` : ""}</p>)}</div>}{request.status !== "Applied" && <div className="admin-request-actions"><textarea value={notes[request.id] || ""} onChange={(e) => setNotes((x) => ({ ...x, [request.id]: e.target.value }))} placeholder="Admin note / rejection reason" /><div><button disabled={busy === request.id} onClick={() => review(request, "Under review")}>Verify payment / under review</button><button className="reject" disabled={busy === request.id} onClick={() => review(request, "Rejected")}>Reject</button><button className="approve" disabled={busy === request.id} onClick={() => review(request, "Approved")}>Approve</button><button className="apply" disabled={busy === request.id} onClick={() => review(request, "Applied")}>Apply change</button></div></div>}{request.appliedAt && <p className="fulfilled">Fulfilled {new Date(request.appliedAt).toLocaleString()} by {request.reviewedByName || "admin"}</p>}{request.reviewedAt && request.status !== "Applied" && <p className="admin-reason">Reviewed {new Date(request.reviewedAt).toLocaleString()} by {request.reviewedByName || "admin"}{request.adminReason ? ` — ${request.adminReason}` : ""}</p>}</article>)}</div>}</div>;
}