import { useEffect, useState } from "react";
import API from "../utils/api";
import "./ProfileChangeRequests.css";

const TRACKS = ["Pre-Engineering", "Pre-Medical", "ICS", "ICom", "FA", "Other / Gap-year"];
const SUBJECTS = [["math", "Mathematics"], ["physics", "Physics"], ["chemistry", "Chemistry"], ["biology", "Biology"], ["english", "English"], ["computer", "Computer Science"]];
const ALLOWED_SUBJECTS = { "Pre-Engineering": ["math", "physics", "chemistry", "english"], "Pre-Medical": ["biology", "physics", "chemistry", "english"], ICS: ["computer", "math", "physics", "english"], ICom: ["math", "english"], FA: ["english"], "Other / Gap-year": ["math", "physics", "chemistry", "biology", "english", "computer"] };
const labels = (items = []) => items.map((item) => SUBJECTS.find(([id]) => id === item)?.[1] || item).join(", ");

export default function ProfileChangeRequestPage({ user }) {
  const [form, setForm] = useState({ requestedTrack: user.academicTrack || "", requestedSubjects: user.academicSubjects || [], reason: "", transactionId: "", receiptProof: "" });
  const [requests, setRequests] = useState([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async () => { try { setRequests((await API.get("/user/profile-change-requests")).data); } catch { setError("Could not load your request history."); } };
  useEffect(() => { load(); }, []);
  const downloadChallan = () => { const html = `<!doctype html><title>Profile Change Fee Challan</title><style>body{font:16px Arial;max-width:720px;margin:48px auto;border:2px solid #0b766f;padding:32px}h1{color:#0b766f}.amount{font-size:24px;font-weight:bold}</style><h1>Entrace.pk — Profile Change Fee Challan</h1><p><b>Student:</b> ${user.name}</p><p><b>Email:</b> ${user.email}</p><p><b>Current profile:</b> ${user.academicTrack || "Not set"}</p><p class="amount">Amount: Rs. 1,000</p><p>Pay Rs. 1,000 using the details provided by administration, then enter the transaction ID and/or upload the receipt on the Profile Change Request page. Genuine typing errors may be corrected by an administrator without payment.</p>`; const url = URL.createObjectURL(new Blob([html], { type: "text/html" })); const a = document.createElement("a"); a.href = url; a.download = "profile-change-challan.html"; a.click(); URL.revokeObjectURL(url); };
  const onReceipt = (event) => { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/") && file.type !== "application/pdf") return setError("Upload an image or PDF receipt."); if (file.size > 2 * 1024 * 1024) return setError("Receipt must be 2 MB or smaller."); const reader = new FileReader(); reader.onload = () => setForm((x) => ({ ...x, receiptProof: reader.result })); reader.readAsDataURL(file); };
  const toggle = (id) => setForm((x) => ({ ...x, requestedSubjects: x.requestedSubjects.includes(id) ? x.requestedSubjects.filter((s) => s !== id) : x.requestedSubjects.length < 5 ? [...x.requestedSubjects, id] : x.requestedSubjects }));
  const submit = async (event) => { event.preventDefault(); setError(""); setMessage(""); setBusy(true); try { const res = await API.post("/user/profile-change-requests", form); setMessage(res.data.message); setForm((x) => ({ ...x, reason: "", transactionId: "", receiptProof: "" })); await load(); } catch (err) { setError(err.response?.data?.error || "Unable to submit your request."); } finally { setBusy(false); } };
  return <div className="profile-change-page"><header><span>Academic profile</span><h1>Request a profile change</h1><p>Your saved profile is locked. Download the demo challan, submit payment evidence, and an administrator will review your request.</p></header><button className="challan-button" type="button" onClick={downloadChallan}>Download demo challan</button><form className="change-request-form" onSubmit={submit}><div className="profile-compare"><div><small>Current track</small><strong>{user.academicTrack || "Not set"}</strong><p>{labels(user.academicSubjects)}</p></div><div><label>Requested track<select value={form.requestedTrack} onChange={(e) => setForm((x) => ({ ...x, requestedTrack: e.target.value, requestedSubjects: x.requestedSubjects.filter((id) => ALLOWED_SUBJECTS[e.target.value].includes(id)) }))}>{TRACKS.map((track) => <option key={track}>{track}</option>)}</select></label></div></div><fieldset><legend>Requested subjects (up to five)</legend><div className="request-subjects">{SUBJECTS.filter(([id]) => ALLOWED_SUBJECTS[form.requestedTrack]?.includes(id)).map(([id, label]) => <label key={id}><input type="checkbox" checked={form.requestedSubjects.includes(id)} onChange={() => toggle(id)} /> {label}</label>)}</div></fieldset><label>Reason for change<textarea required value={form.reason} onChange={(e) => setForm((x) => ({ ...x, reason: e.target.value }))} placeholder="Explain why you need this change." /></label><label>Transaction ID (optional when a receipt is uploaded)<input value={form.transactionId} onChange={(e) => setForm((x) => ({ ...x, transactionId: e.target.value }))} placeholder="e.g. bank / wallet reference" /></label><label>Payment receipt (optional when a transaction ID is entered)<input type="file" accept="image/*,application/pdf" onChange={onReceipt} />{form.receiptProof && <small>Receipt attached.</small>}</label>{error && <p className="request-error">{error}</p>}{message && <p className="request-success">{message}</p>}<button className="request-primary" disabled={busy}>{busy ? "Submitting…" : "Submit change request"}</button></form><section className="request-history"><h2>Your request history</h2>{requests.length === 0 ? <p>No requests submitted yet.</p> : requests.map((request) => <article key={request.id}><div><strong>{request.requestedTrack}</strong><p>{labels(request.requestedSubjects)} · submitted {new Date(request.createdAt).toLocaleString()}</p></div><span className={`request-status ${request.status.replaceAll(" ", "-").toLowerCase()}`}>{request.status}</span>{request.adminReason && <p className="admin-reason">Admin note: {request.adminReason}</p>}{request.appliedAt && <p className="fulfilled">Fulfilled {new Date(request.appliedAt).toLocaleString()} by {request.reviewedByName || "admin"}</p>}</article>)}</section></div>;
}